name: mobilecomfy
description: A lightweight Android client for the LazyComfy custom node.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.10
  http: ^1.2.2
  shared_preferences: ^2.3.3
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
